# Generated by Django 5.2.5 on 2025-09-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Kullanıcının e-posta adresini doğrulayıp doğrulamadığını belirtir.",
                verbose_name="E-posta Doğrulandı",
            ),
        ),
    ]
