# Pre-commit hooks configuration
# See https://pre-commit.com for more information
repos:
  # Code formatting
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]
        files: ^backend/

  # Import sorting  
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black, --line-length=88]
        files: ^backend/

  # Linting
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203,W503]
        files: ^backend/

  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Git hygiene
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=500]
      
      # Python checks
      - id: check-python-check-syntax
      - id: check-ast
      - id: debug-statements
      
      # JSON/YAML validation
      - id: check-json
      - id: check-yaml
        exclude: ^docker-compose.*\.yml$
      
      # Security
      - id: detect-private-key

  # Django specific
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.15.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "5.0"]
        files: ^backend/

  # Security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-r, --skip, B101,B601]
        files: ^backend/

# Configuration
default_language_version:
  python: python3.11

# Skip hooks for specific files
exclude: |
  (?x)^(
    .*migrations/.*\.py|
    .*__pycache__/.*|
    .*\.pyc
  )$
