version: '3.8'

services:
  # Next.js Frontend (Opsiyonel)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bp_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

  # Nginx with Frontend Support
  nginx-frontend:
    build:
      context: ./nginx
      dockerfile: Dockerfile.frontend
    container_name: bp_nginx_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/static
      - media_volume:/media
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
