# Generated by manual migration

from django.db import migrations


def transfer_name_data(apps, schema_editor):
    """Transfer first_name and last_name from User to Profile"""
    User = apps.get_model("accounts", "User")
    Profile = apps.get_model("accounts", "Profile")

    # Get all users
    users = User.objects.all()

    for user in users:
        # Get or create profile for this user
        profile, created = Profile.objects.get_or_create(user=user)

        # Transfer name data
        profile.first_name = user.first_name or ""
        profile.last_name = user.last_name or ""
        profile.save()


def reverse_transfer_name_data(apps, schema_editor):
    """Reverse: Transfer first_name and last_name from Profile back to User"""
    User = apps.get_model("accounts", "User")
    Profile = apps.get_model("accounts", "Profile")

    # Get all profiles
    profiles = Profile.objects.all()

    for profile in profiles:
        user = profile.user
        user.first_name = profile.first_name or ""
        user.last_name = profile.last_name or ""
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_add_name_fields_to_profile"),
    ]

    operations = [
        migrations.RunPython(transfer_name_data, reverse_transfer_name_data),
    ]
