# Generated by manual migration

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_transfer_name_data_to_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
    ]
